---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ouoto9rt7iqd/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
  - /bin/cp -R css $DEPLOYPATH
  - /bin/cp -R fonts $DEPLOYPATH
  - /bin/cp -R js $DEPLOYPATH
  - /bin/cp -R lb $DEPLOYPATH